spring:
    application:
        name: spring-api
    datasource:
        driver-class-name: org.postgresql.Driver
        url: jdbc:postgresql://localhost:5432/payroll
        username: rupam
        password: 957535
    jpa:
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        hibernate:
            ddl-auto: none
        properties:
            hibernate:
                format_sql: true
        show-sql: true
    jackson:
        default-property-inclusion: NON_NULL
#    mvc:
#        throw-exception-if-no-handler-found: true
#        static-path-pattern: /static
##        static-path-pattern: /swagger*
#    resources:
#        add-mappings: false

springdoc:
    packagesToScan: com.spring.country.api